project:
  type: book
  output-dir: docs
book:
  title: "Praktikum Ramon Füglister"
  author: "Ramon Füglister"
  date: "14.4.2025"
  chapters:
    - index.qmd
    - 1_Automatisierte_Literaturrecherche.qmd
    - references.qmd


bibliography: references.bib
csl: apa.csl
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
